data:
  dataset: "coco"
  images_path: "datasets/coco"
  captions_path: "datasets/coco/caption_datasets/dataset_coco.json"

loss:
  cls_label_path: "datasets/coco/coco_multilabel_map.pt"

paraphraser:
  paths:
    mistral: "datasets/coco/caption_rewrites_mistral-7b-instruct-v0.2.json"
    llama:   "datasets/coco/caption_rewrites_meta-llama-3-8b-instruct.json"
