program: run.py
method: grid
metric:
  name: val/t2i_r1
  goal: maximize

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "configs/config_flickr.yaml"
  - ${args}

parameters:
  # --- FNE Parameters ---
  mining.enabled:
    value: true
  
  loss.use_clip_loss:
    value: false
  
  mining.fne_threshold:
    values: [0.90, 0.95, 0.98]

  # --- Training Settings ---
  training.epochs:
    value: 20
    
  logging.save_freq:
    value: 1  # Updates last_model.pth every epoch
